#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")

VERSION=3.2.2

kubectl delete configmap --selector=app.kubernetes.io/part-of=ueransim --ignore-not-found=true
kubectl delete deployments --selector=app.kubernetes.io/part-of=ueransim --ignore-not-found=true
#kubectl delete services --selector=app.kubernetes.io/part-of=ueransim --ignore-not-found=true
kubectl wait pods --selector=app.kubernetes.io/part-of=ueransim --for=delete || true
#kubectl wait services --selector=app.kubernetes.io/part-of=ueransim --for=delete || true


function d() {
    VERSION=$VERSION \
    COMPONENT=$1 \
    AMFIP=$2 \
    IMAGE="localhost:5000/ueransim:$VERSION" \
    envsubst < "$HERE/manifests/component.yaml" |
    kubectl apply -f -
}

AMFIP=$(kubectl get svc amf -o jsonpath='{.spec.clusterIP}')
VERSION=$VERSION \
AMFIP=$AMFIP \
envsubst < "$HERE/manifests/gnb-configmap.yaml" |
kubectl create -f -

d gnb $AMFIP
#d ue

