apiVersion: v1
data:
  gnb.yaml: |
    mcc: '001'          # Mobile Country Code value
    mnc: '01'           # Mobile Network Code value (2 or 3 digits)

    nci: '0x000000010'  # NR Cell Identity (36-bit)
    idLength: 32        # NR gNB ID length in bits [22...32]
    tac: 12345          # Tracking Area Code

    linkIp: $GNB_IP     # gNB's local IP address for Radio Link Simulation (Usually same with local IP)
    ngapIp: "10.28.3.9" # gNB's local IP address for N2 Interface 
    gtpIp: "10.28.4.9"  # gNB's local IP address for N3 Interface 

    # List of AMF address information
    amfConfigs:
      - address: "10.28.3.8"
        port: 38412

    # List of supported S-NSSAIs by this gNB
    slices:
      - sst: 1

    # Indicates whether or not SCTP stream number errors should be ignored.
    ignoreStreamIds: true
kind: ConfigMap
metadata:
  name: gnb
  labels:
    app.kubernetes.io/name: gnb
    app.kubernetes.io/instance: gnb
    app.kubernetes.io/version: $VERSION
    app.kubernetes.io/component: 5g
    app.kubernetes.io/part-of: ueransim
    app.kubernetes.io/managed-by: ueransim