apiVersion: v1
data:
  gnb.yaml: |
    mcc: '001'          # Mobile Country Code value
    mnc: '01'           # Mobile Network Code value (2 or 3 digits)

    nci: '0x000000010'  # NR Cell Identity (36-bit)
    idLength: 32        # NR gNB ID length in bits [22...32]
    tac: 12345          # Tracking Area Code

    linkIp: 0.0.0.0   # gNB's local IP address for Radio Link Simulation (Usually same with local IP)
    ngapIp: 0.0.0.0   # gNB's local IP address for N2 Interface (Usually same with local IP)
    gtpIp: 0.0.0.0    # gNB's local IP address for N3 Interface (Usually same with local IP)

    # List of AMF address information
    amfConfigs:
      - address: $AMFIP
        port: 38412

    # List of supported S-NSSAIs by this gNB
    slices:
      - sst: 1

    # Indicates whether or not SCTP stream number errors should be ignored.
    ignoreStreamIds: true
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-13T11:36:58Z"
  name: gnb
  labels:
    app.kubernetes.io/name: gnb
    app.kubernetes.io/instance: gnb
    app.kubernetes.io/version: $VERSION
    app.kubernetes.io/component: 5g
    app.kubernetes.io/part-of: ueransim
    app.kubernetes.io/managed-by: ueransim
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:gnb.yaml: {}
    manager: kubectl-create
    operation: Update
    time: "2021-07-13T11:36:58Z"
  namespace: default
  resourceVersion: "259014"
  uid: 01cf8e44-3369-46f7-bc03-b1d4f052a20f
