#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")

POD=$(kubectl get pods -l app.kubernetes.io/name=gnb --output=jsonpath="{.items[0].metadata.name}")

kubectl logs -f  $POD
