#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")

POD=$(kubectl get pods -l app.kubernetes.io/name=gnb --output=jsonpath="{.items[0].metadata.name}")


touch $HERE/5gran.fifo
kubectl exec  $POD -- /usr/sbin/tcpdump -s 0 -n -w - -U -i eth0 > $HERE/5gran.fifo 
