#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")

POD=$(kubectl get pods -l app.kubernetes.io/name=ue --output=jsonpath="{.items[0].metadata.name}")


kubectl exec  $POD -- ping -I uesimtun0 www.google.es
